name: Debug Build

on:
  push:
    branches-ignore: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "NewHorizons/Schemas/**"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  Build:
    uses: './.github/workflows/build.yaml'
    with:
      build_type: Debug
  Update_Schemas:
    name: 'Update Schemas'
    needs: Build
    uses: './.github/workflows/update_schemas.yml'
    with:
      artifact_name: NewHorizons-Schemas-Debug