name: Update Schemas

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        description: 'Name of the artifact to download and check against'
        type: string

jobs:
  update_schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: NewHorizons/Schemas/

      - name: Verify Changed Schemas
        uses: tj-actions/verify-changed-files@v9.1
        id: changed_files
        with:
          files: NewHorizons/Schemas/**
          
      - name: Commit Schemas
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add NewHorizons\Schemas\**
          git commit -m "Updated Schemas"
          
      - name: Push Schemas
        if: ${{ (steps.changed_files.outputs.files_changed == 'true') && (github.event_name != 'pull_request') }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}
